# LLM101 第二模块：大模型基础推理与提示词工程
# 专用Conda环境配置文件
name: llm101-prompt

channels:
  - conda-forge  # 开源社区维护的高质量包仓库
  - defaults     # Anaconda官方默认软件源

dependencies:
  # Python基础环境
  - python=3.10.18  # Python解释器，使用稳定版本3.10.18
  - pip             # Python包管理器

  # 通过pip安装的包
  - pip:
    # === 大模型API调用相关 ===
    - openai==1.61.0              # OpenAI官方SDK，用于调用GPT系列模型
    - python-dotenv==1.0.0        # 环境变量管理，安全存储API密钥
    - requests==2.28.0            # HTTP请求库，用于API调用和网络请求
    
    # === 数据处理与验证 ===
    - pydantic==2.0.0             # 数据验证和类型检查，确保数据质量
    - pyyaml==6.0                 # YAML文件解析，用于配置文件读取
    
    # === 模板引擎与用户界面 ===
    - jinja2==3.1.0               # 模板引擎，用于提示词模板管理
    - click==8.0.0                # 命令行界面框架，构建CLI工具
    - colorama==0.4.6             # 跨平台彩色终端输出，美化命令行界面
    - tqdm==4.64.0                # 进度条显示，提升用户体验
    
    # === 数据分析与处理 ===
    - pandas==2.0.0               # 数据分析和处理库，处理结构化数据
    - numpy==1.24.0               # 数值计算基础库，支持数组操作
    
    # === 数据可视化 ===
    - matplotlib==3.6.0           # 基础绘图库，创建图表和可视化
    - seaborn==0.12.0             # 统计数据可视化，美化图表样式
    
    # === 交互式开发环境 ===
    - jupyter==1.0.0              # Jupyter Notebook，支持交互式开发和实验
    - ipython==8.10.0             # 增强的Python交互式解释器
    
    # === 代码质量保证工具 ===
    - pytest==7.2.0              # 单元测试框架，保证代码质量
    - black==23.1.0               # 代码格式化工具，统一代码风格
    - flake8==6.0.0               # 代码风格检查工具，发现潜在问题
    - isort==5.12.0               # import语句排序工具，整理导入语句
    - mypy==1.0.0                 # 静态类型检查工具，提高代码可靠性 